[package]
name = "embedder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
wasmtime = "14.0.4"
wasmtime-wasi = "14.0.4"

[[bin]]
name = "embedder"
path = "src/embedder.rs"